
export const metadata = {
  title: 'TRIFONOVA ALINA',
  description: 'Generated by Next.js',
}

import './global.css'

import {Montserrat} from 'next/font/google'

const montserrat = Montserrat ({
  subsets:["latin"],
  display:"swap"
})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body style={{margin:0}}>{children}</body>
    </html>
  )
}
